# Generated by Django 4.2.7 on 2024-03-27 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
