# Generated by Django 4.2.7 on 2024-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_address_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='other',
            field=models.CharField(default='', max_length=50),
        ),
    ]
