# Generated by Django 4.2.7 on 2024-04-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_address_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='address',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
