# Generated by Django 4.2.7 on 2024-07-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_order',
        ),
    ]
