# Generated by Django 4.2.7 on 2024-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('C1', 'Confirm'), ('Q2', 'In the review queue'), ('R3', 'Received from the seller'), ('P4', 'Preparing the order'), ('D5', 'Delivery to the post office'), ('D6', 'Delivery to the customer'), ('R7', 'Return of the cost due to lack of stock'), ('N8', 'Not Paid')], default='In the review queue', max_length=2),
        ),
    ]
